spring.application.name=cpcompass

server.port=${PORT:8080}
JWT_SECRET=mySuperSecretKeyForCpCompassApplication123456789

#spring.datasource.url=${SPRING_DATASOURCE_URL}
#spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
#spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

spring.datasource.url=jdbc:postgresql://ep-raspy-hall-aoiml3a9-pooler.c-2.ap-southeast-1.aws.neon.tech/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_ecx6fDnQum8s

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true

#spring.data.redis.host=${SPRING_REDIS_HOST:localhost}
#spring.data.redis.port=${SPRING_REDIS_PORT:6379}
#spring.data.redis.password=${SPRING_REDIS_PASSWORD:}

spring.data.redis.host=careful-pipefish-159700.upstash.io
spring.data.redis.port=6379
spring.data.redis.password=gQAAAAAAAm_UAAIgcDJjMDBlYmE3YWU4M2E0YjU4ODZlOWNlM2MxZTc5NjdkNg
spring.data.redis.ssl.enabled=true